[build]
  command = "npm run build"
  # שים כאן את התיקייה הנכונה לפרויקט שלך: "build" (CRA) או "dist" (Vite)
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

# דוגמה לדילוג על build אם רק README השתנה:
# ignore = "git diff --quiet HEAD^ HEAD README.md"
